# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Setup Node
      run: npm i package.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Update appsettings.json file uri
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: Neoflix/appsettings.json
        old-string: NEO4J_URI
        new-string: ${{ secrets.NEO4J_URI }}

    - name: Read file
      run: echo Neoflix/appsettings.json
    
    - name: Update appsettings.json file username
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "NEO4J_USERNAME"
        replace: ${{ secrets.NEO4J_USERNAME }}
        include: "**./Neoflix/appsettings.json"

    - name: Update appsettings.json file password 
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "NEO4J_PASSWORD"
        replace: ${{ secrets.NEO4J_PASSWORD }}
        include: "**./Neoflix/appsettings.json"
           
    - name: Read appsettings.json
      run: cat Neoflix/appsettings.json
      
    - name: Install Driver
      run: dotnet add Neoflix package Neo4j.Driver
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --logger "console;verbosity=detailed" --filter "Neoflix.Challenges._01_ConnectToNeo4j"
