# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Setup Node
      run: npm i package.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Decrypt large secret
      run: ./decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - name: 
      run: |
        mv $HOME/secrets/appsettings.json Neoflix/appsettings.json
        cat Neoflix/appsettings.json

    - name: Install Driver
      run: dotnet add Neoflix package Neo4j.Driver

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --logger "console;verbosity=detailed" --filter "Neoflix.Challenges._01_ConnectToNeo4j"
